export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const DEC_CART_PRODUCT = "DEC_CART_PRODUCT";
export const CLEAR_CART_PRODUCT = "CLEAR_CART_PRODUCT";
export const SET_CART_PRODUCT = "SET_CART_PRODUCT";

export const SET_USER_DATA = "SET_USER_DATA";
